### ISSUE TITLE
Ocassional errors with Tagbox

### ISSUE THREAD

**Issue by arsaboo** [robmarkcole/HASS-Machinebox-Tagbox#1]
Keep seeing these errors once in a while for one of the cameras. I have four cameras setup with Tagbox and I can see all the cameras in HA and the tagbox instance is working. 
```
Log Details (ERROR)
Mon Apr 02 2018 11:51:35 GMT-0400 (Eastern Daylight Time)

Update for image_processing.tagbox_patio fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/image_processing/__init__.py", line 136, in async_update
    yield from self.async_process_image(image)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/image_processing/tagbox.py", line 77, in process_image
    self._state = max(tags.keys(), key=(lambda k: tags[k]))
ValueError: max() arg is an empty sequence
```

**Comment by robmarkcole** [comment]
Should be resolved in https://github.com/robmarkcole/HASS-Machinebox-Tagbox/commit/1bcdda514bb3b780a424a5535a9d512aa7a46874
